# Generated by Django 3.2 on 2022-04-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='agent',
            new_name='practitioner',
        ),
    ]
